#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Byron Williams
# SPDX-License-Identifier: MIT
#
# Regenerate requirements-search.txt: the hash-pinned closure of
# requirements-search.in, with versions and hashes taken from poetry.lock.
# Needs poetry (with poetry-plugin-export) and uv on PATH.
set -euo pipefail

cd "$(dirname "$0")/.."
work="$(mktemp -d)"
trap 'rm -rf "${work}"' EXIT

poetry export --only main --format requirements.txt -o "${work}/full.txt" >/dev/null

# Constraints: every locked package pinned, no hashes or markers.
sed -E -n 's/^([A-Za-z0-9._-]+==[^ ;]+).*/\1/p' "${work}/full.txt" > "${work}/constraints.txt"

uv pip compile requirements-search.in -c "${work}/constraints.txt" \
  --python-version 3.12 --python-platform linux --no-header --no-annotate \
  -o "${work}/closure.txt" >/dev/null

python3 - "${work}/full.txt" "${work}/closure.txt" <<'PY' > requirements-search.txt
import re
import sys

full_path, closure_path = sys.argv[1:3]


def norm(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


wanted = {
    norm(m.group(1))
    for line in open(closure_path, encoding="utf-8")
    if (m := re.match(r"^([A-Za-z0-9._-]+)==", line))
}

entries, current = [], []
for line in open(full_path, encoding="utf-8"):
    if re.match(r"^[A-Za-z0-9]", line):
        current = [line]
        entries.append(current)
    elif current:
        current.append(line)

print("# Generated by docker/export-search-requirements.sh from poetry.lock; do not edit.")
found = set()
for entry in entries:
    name = norm(re.match(r"^([A-Za-z0-9._-]+)==", entry[0]).group(1))
    if name in wanted:
        found.add(name)
        # Markers are dropped: the image is a single known platform.
        entry[0] = re.sub(r"\s*;[^\\]*", " ", entry[0])
        print("".join(entry), end="")
missing = wanted - found
if missing:
    sys.exit(f"packages missing from poetry.lock export: {sorted(missing)}")
PY
echo "wrote requirements-search.txt"
